name: Wails build

on:
  push:
    tags:
      - "v*"

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'blive-start-helper'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'blive-start-helper'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'blive-start-helper'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v3
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.23'
          wails-version: "v2.9.0"