name: Wails build

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags
  release:
    types: [created]

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'blive-start-helper'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'blive-start-helper'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'blive-start-helper'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wails
        uses: ./.github/actions/wails-build-action
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.23'
          node-version: 'v22.15.1'
          wails-version: "v2.9.0"