// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLiveCategory() {
  return window['go']['main']['App']['GetLiveCategory']();
}

export function GetQRCode() {
  return window['go']['main']['App']['GetQRCode']();
}

export function GetRoomStatus(arg1) {
  return window['go']['main']['App']['GetRoomStatus'](arg1);
}

export function StartLive(arg1, arg2) {
  return window['go']['main']['App']['StartLive'](arg1, arg2);
}

export function StopLive() {
  return window['go']['main']['App']['StopLive']();
}

export function UpdateLiveInfo(arg1, arg2) {
  return window['go']['main']['App']['UpdateLiveInfo'](arg1, arg2);
}

export function UserInfo() {
  return window['go']['main']['App']['UserInfo']();
}
