// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {model} from '../models';

export function GetLiveCategory():Promise<main.LiveCategory>;

export function GetQRCode():Promise<model.QRCode>;

export function GetRoomStatus(arg1:number):Promise<main.RoomStatus>;

export function StartLive(arg1:string,arg2:number):Promise<model.Rtmp>;

export function StopLive():Promise<void>;

export function UpdateLiveInfo(arg1:string,arg2:number):Promise<void>;

export function UserInfo():Promise<main.User>;
